---
- name: Install deps
  yum:
    name:
      - policycoreutils-python
      - selinux-policy-devel
    state: present
  when: ansible_distribution == 'CentOS'

- name: Check enabled SELinux modules
  shell: semanage module -l
  register: enabled_modules
  when: ansible_distribution == 'CentOS'

- name: Copy hera_selinux policy
  copy: src=hera_selinux.te dest=/root/hera_selinux.te
  register: dest_hera_selinux_te
  when: ansible_distribution == 'CentOS'

- name: Compile hera_selinux policy
  shell: "make -f /usr/share/selinux/devel/Makefile hera_selinux.pp && semodule -i hera_selinux.pp"
  args:
    chdir: /root/
  when: "ansible_distribution == 'CentOS' and enabled_modules.stdout.find('hera_selinux') == -1 or dest_hera_selinux_te.changed"
...