---

- hosts: localhost
  become: yes
  become_user: root
  vars:
    bench_repo_path: "/Users/{{ ansible_user_id }}/.bench"
    bench_path: "/Users/{{ ansible_user_id }}/hera-bench"
  tasks:
    # install pre-requisites
    - name: install prequisites
      homebrew:
        name:
          - cmake
          - redis
          - postgresql@16
          - nodejs
        state: present

    # install wkhtmltopdf
    - name: cask installs
      homebrew_cask:
        name:
          - wkhtmltopdf
        state: present

    - name: configure PostgreSQL
      include_tasks: roles/postgresql/tasks/main.yml

    # setup hera-bench
    - include_tasks: includes/setup_bench.yml

    # setup development environment
    - include_tasks: includes/setup_dev_env.yml
      when: not production

...